### ISSUE TITLE
Subtask #6: Related to #69 Configure Statistics - Run Tests, and Confirm whether Average Speed is being displayed correctly

### ISSUE THREAD

**Issue by aryansaxena094** [rilling/OSMDashboardConcordia#102]
## Description

Run the pre-existing tests in the test file - 
- WaypointTest.java
- MapUtilsTest.java

And verify with screenshots that the enhancement is added for Average Speed (For both Mile/Hour and Kilometer/Hour)

**Comment by harsh-tank** [comment]
Description :

Examine the changes using Java testing framework jUnit 

**Screenshots** 

WaypointTest.java

![image](https://github.com/rilling/OSMDashboardConcordia/assets/65907699/7b791db8-dc85-4b98-8b13-c9d9f5c04d4b)

Validated the functionality with jUnit assert method to determine whether the result generated by the method matches the expected values.

TestCase 1: It verifies whether the resulting Waypoint object has the expected latitude, longitude, and name passed as URI String.

TestCase 2:  This case verifies if the resulting Waypoint object has the expected latitude and longitude as passed an object, but the name is expected to be null.

TestCase 3:  This test examines the case where the Geo URI contains only the latitude and longitude without any additional query parameters and the name is expected to be null

 MapUtilsTest.java

![image](https://github.com/rilling/OSMDashboardConcordia/assets/65907699/756e7b5e-e399-491f-b97e-9132b513eafa)

Here the TestSuite aims to ensure that the isValid() method returns the expected results validating the pair of latitude and longitude according to geographic coordinate constraints.
