### ISSUE TITLE
#Subtask 5 - Related to the issue #67 . Validate the build and confirm if the app is working post the changes.

### ISSUE THREAD

**Issue by msrana25** [rilling/OSMDashboardConcordia#116]
**Is your feature request related to a problem? Please describe.**
Related to the issue #67. Validate the build and confirm if the app is working post the changes.

**Comment by aaryaparikh** [comment]
App validated and built. Runs well post changes.

**Comment by msrana25** [comment]
![aarya](https://github.com/rilling/OSMDashboardConcordia/assets/99360954/62d205f7-13f8-451a-9acc-fa660478954e)
