### ISSUE TITLE
Fix Sonar Issue: Missing default clause to the switch statement

### ISSUE THREAD

**Issue by UIcoder511** [rilling/OSMDashboardConcordia#12]
**Describe the technical debt**
Missing default case to the switch statement

![bug](https://github.com/rilling/OSMDashboardConcordia/assets/58945222/3d134ad0-9666-4025-b10b-b25a47429efb)

**Why is this an issue**
The default clause is used to handle cases not explicitly covered by the other case statements. In Java, it's not required to include a default clause, but it's often considered good practice to include one to handle unexpected or future cases

**Proposed solution**
Add the 'default' clause to the switch statement.  The default block can be left empty, or can be added some logging or specific handling for unexpected values.

**Technical information**
- Device: Pixel 7 Pro API 34
- OS: Android 14
- OSM Dashboard version: 3.0.0

**Comment by shashidharkrovvidi** [comment]
added empty default case and closing the issue
https://github.com/rilling/OSMDashboardConcordia/pull/13
