### ISSUE TITLE
Fix Sonar Issue: Consitency Issue | String[] PROJECTION is declared as 'public static'

### ISSUE THREAD

**Issue by shashidharkrovvidi** [rilling/OSMDashboardConcordia#18]
**Describe the technical debt**
String[] PROJECTION is declared as 'public static'

URL: https://github.com/rilling/OSMDashboardConcordia/blob/Group-15/src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/Waypoint.java

Why is this an issue?

Mutable static members of classes and enumerations which are accessed directly, rather than through getters and setters, should be protected to the degree possible. That can be done by reducing visibility or making the field final if appropriate.

Note that making a mutable field, such as an array, final will keep the variable from being reassigned, but doing so has no effect on the mutability of the internal state of the array (i.e. it doesn’t accomplish the goal).

**Proposed solution**
Make String[] PROJECTION 'protected'

Technical information
![issue](https://github.com/rilling/OSMDashboardConcordia/assets/146649461/1fb833e4-31ca-444b-89ff-579916337106)

    Device: Pixel 7 Pro API 34
    OS: Android 14
    OSM Dashboard version: 3.0.0

**Comment by UIcoder511** [comment]
Changed visibility of PROJECTION variable to "protected".
Closing the issue.

![image](https://github.com/rilling/OSMDashboardConcordia/assets/58945222/9f6c2292-d9da-4f6c-b3c0-3ea780075cbe)
