### ISSUE TITLE
Maps are missing a legend

### ISSUE THREAD

**Issue by rilling** [rilling/OSMDashboardConcordia#67]
**Is your feature request related to a problem? Please describe.**
It is not clear what are the different colours of the tracks - what are they correlating to?
 

**Describe the solution you'd like**
Provide a clear legend - if they reflect a speed range this should be displayed.

Currently:
![Screenshot_20231026-210105](https://github.com/rilling/OSMDashboardConcordia/assets/1248571/14b6bbb7-cb47-4466-9492-b43898fb6d17)

It would be nice to have a legend like in this example:

![Screenshot_20231026-204352](https://github.com/rilling/OSMDashboardConcordia/assets/1248571/1a4066a1-c641-4c8c-96e2-75527a276cf0)

**Comment by msrana25** [comment]
Issue:- Maps are missing a legend. It is not clear what are the different colors of the tracks - what are they correlating to?

Solution:- When using the 'Color by speed' option in user settings. The polyline on the map will be colored according to the below criteria,

Speed = 0, polyline would be green
Speed < Avg speed, polyline would be yellow
Speed < Avg speed, polyline would be orange
Avgspeed< Speed <Max Speed, polyline would be blue
Speed = MaxSpeed, polyline would be red.

A legend would be shown which would reflect the information stated above, with some text data included as well.

**Comment by msrana25** [comment]
Currently being worked upon in the group branch [here](https://github.com/rilling/OSMDashboardConcordia/tree/Group-14(Case-Study2)).

**Comment by msrana25** [comment]
Implemented the functionality. 

### Before:-
![Screenshot_20231124-194358_OSM Dashboard](https://github.com/rilling/OSMDashboardConcordia/assets/99360954/c2ae7520-dfae-48e9-a16d-ca14e4be2e5e)


### **After the enhancement:-**
![Screenshot_20231124-193829_OSM Dashboard (Debug)](https://github.com/rilling/OSMDashboardConcordia/assets/99360954/5c5eb521-64c2-4ac3-8047-ae3f9d6f53e2)
![Screenshot_20231124-194018_OSM Dashboard (Debug)](https://github.com/rilling/OSMDashboardConcordia/assets/99360954/07bf5bd3-a983-45d1-8a8c-777b0d716429)

**Comment by msrana25** [comment]
Latest changes updated in a separate branch [here](https://github.com/rilling/OSMDashboardConcordia/tree/Group-14(CaseStudy2---latest))

**Comment by msrana25** [comment]
**As the leader of group 14, completed the following tasks,**
1. Went through the codebase 
2. Identified the components (files) to which changes needed to be made for implementing the enhancement.
3.  Drilled down further to understand the working of these components and what changes were needed to be made for this functionality
4. Based on the above steps, created sub-issues stating what code changes were needed and where. Links to sub-issues are below.
[Subtask 1
](https://github.com/rilling/OSMDashboardConcordia/issues/90)[Subtask 2](https://github.com/rilling/OSMDashboardConcordia/issues/91)
[Subtask 3](https://github.com/rilling/OSMDashboardConcordia/issues/110)
[Subtask 4](https://github.com/rilling/OSMDashboardConcordia/issues/115)
[Subtask 5](https://github.com/rilling/OSMDashboardConcordia/issues/116)

6. Understood the group dependencies of our assigned folder and updated the wiki as well.
7. Worked with the group, the changes were implemented, committed these changes to the main branch

**Comment by msrana25** [comment]
Working apk equipped with the required enhacement is available for download [here](https://drive.google.com/file/d/1K8RP686UNwj2b_AebaoVVcYZq82i-Ux7/view?usp=sharing)

**Comment by msrana25** [comment]
**The feature was added and the changes were merged as part of this** [commit](https://github.com/rilling/OSMDashboardConcordia/pull/120).
