### ISSUE TITLE
Configure statistic - entries are redundant

### ISSUE THREAD

**Issue by rilling** [rilling/OSMDashboardConcordia#68]
**Is your feature request related to a problem? Please describe.**
There are redundant entries (metric/imperial) are separate entries

**Describe the solution you'd like**
Based on the unit setting specified in OpenTracks, these setting should automatically applied.  There is no need to have separate selection options for metric and Imperial. See below

 
![Screenshot_20231026-210712](https://github.com/rilling/OSMDashboardConcordia/assets/1248571/67e35d7d-f370-4bd3-99f7-a3dddbe3ed4b)

**Describe alternatives you've considered**

**Additional context**

**Comment by raveena-choudhary** [comment]
This issue is resolved, and documented in pdf to be shared for case study 2. Hence, closing this ticket.
