### ISSUE TITLE
Configure statistics - Average speed is missing

### ISSUE THREAD

**Issue by rilling** [rilling/OSMDashboardConcordia#69]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to select and display on the map the average speed statistic.

**Describe the solution you'd like**
Add an Selection option - Average Speed. This info can either be computed or should be available in OpenTracks as a function. Units should be the same as specified in OpenTracks (see also issue #68 )

![Screenshot_20231026-210712](https://github.com/rilling/OSMDashboardConcordia/assets/1248571/f728dfe6-6d0f-441c-b4a0-d0f91d49d255)

**Comment by aryansaxena094** [comment]
Reference Issue - Divided into different Subtasks - #92, #95, #97, #99, #100, #102 
Added the Selection option - Average Speed. Post coordination with Group 16, same units were used for uniformity from Issue #68. 
Average speed added for Mi/H and Km/h both. (Fetching from TrackStatistics.java)
