### ISSUE TITLE
Sub Task #1 : Creation of entry : Show distance marker on Map in the Settings Option

### ISSUE THREAD

**Issue by shashidharkrovvidi** [rilling/OSMDashboardConcordia#81]
This is the first subtask of the issue https://github.com/rilling/OSMDashboardConcordia/issues/70

**Comment by sameer1130** [comment]
Distance Interval Checkbox has been made.

![image](https://github.com/rilling/OSMDashboardConcordia/assets/58945222/30949c3d-702c-45fb-b6a4-4a8f3be530b7)

 merged in branch: group_15_case_study_deliverable2.
 commit id : 9c5dcd2
