### ISSUE TITLE
Sub Task #2: specify at what interval the distance marker should be displayed 

### ISSUE THREAD

**Issue by shashidharkrovvidi** [rilling/OSMDashboardConcordia#82]
This is the second subtask for https://github.com/rilling/OSMDashboardConcordia/issues/70.
after the entry 'Show distance markers on map' is selected, the user should be able to specify the intervals at which distance markers should be placed on the track

**Comment by tspatel11019** [comment]
wrong issue linked

**Comment by shashidharkrovvidi** [comment]
the user should be able to specify the intervals at which distance markers should be placed on the track (default value is 10). For that Distance Interval should be clicked from the menu

![image](https://github.com/rilling/OSMDashboardConcordia/assets/58945222/8849b3d1-2217-4743-a0b8-e82a266d65e9)


![subtask 2](https://github.com/rilling/OSMDashboardConcordia/assets/146649461/8b15fcaf-e9d5-4099-a065-ad0c4a86d7d4)
