### ISSUE TITLE
Sub Task #3: Placing the markers at the intervals

### ISSUE THREAD

**Issue by shashidharkrovvidi** [rilling/OSMDashboardConcordia#83]
This is the 3rd subtask for https://github.com/rilling/OSMDashboardConcordia/issues/70
after user selects the required interval value, markers should appear on the track at the interval selected by the user.

**Comment by UIcoder511** [comment]
added function to place markers at specified distance interval (km/miles) on the map
Commit Link: 3e9b11b

**Comment by UIcoder511** [comment]
modified the function to place markers and the function to create bitmap from drawable, using the text-view drawable from #86 and the blue maker drawable from #84 
Commit Link: 0f6d0bb29e8602d133d1e04b0f606111fd4405a7

**Comment by UIcoder511** [comment]
![WhatsApp Image 2023-11-23 at 22 58 05_f5c8e068](https://github.com/rilling/OSMDashboardConcordia/assets/58945222/75a1baaa-5691-48c9-bb79-dfa359d2aaca)
