### ISSUE TITLE
Sub Task #4: create blue circle drawable

### ISSUE THREAD

**Issue by shashidharkrovvidi** [rilling/OSMDashboardConcordia#84]
this is fourth subtask to https://github.com/rilling/OSMDashboardConcordia/issues/70 to create markers with dynamic text inside them which would be displayed on the track.

**Comment by UIcoder511** [comment]
Created blue circle drawable for the markers
![image](https://github.com/rilling/OSMDashboardConcordia/assets/58945222/e24e379b-82a1-45cd-bc54-2cee2ce2d925)

Commit Link: 24dd335
