### ISSUE TITLE
Sub Task #6: Create text view drawable to use with the blue circle drawable for the dynamic text inside it

### ISSUE THREAD

**Issue by shashidharkrovvidi** [rilling/OSMDashboardConcordia#86]
Main issue: https://github.com/rilling/OSMDashboardConcordia/issues/70

**Comment by tspatel11019** [comment]
A text view drawable for the dynamic text to be used with the blue circle drawable.
![image](https://github.com/rilling/OSMDashboardConcordia/assets/58945222/36779ecc-5064-40b9-8e1e-59e4abe18cce)

Location: src/main/res/layout/view_custom_marker.xml
With necessary changes, merged in branch: group_15_case_study_deliverable2.

commit id: 4796011

**Comment by tspatel11019** [comment]
The following shows the informed blue pins on the openTracks Map

Execution image:
![WhatsApp Image 2023-11-26 at 3 38 21 AM (2)](https://github.com/rilling/OSMDashboardConcordia/assets/147454268/ae416024-73f1-4d4a-9c4b-907382aacfcd)
