### ISSUE TITLE
#Subtask 1 - Related to the issue #67: Maps are missing a legend - Color coding based on Speed 

### ISSUE THREAD

**Issue by msrana25** [rilling/OSMDashboardConcordia#90]
**Is your feature request related to a problem? Please describe.**
Related to the issue #67 . Maps are missing a legend

**Describe the solution you'd like**
In MapActivity.java, the code needs to be incorporated to set the color of the track (polyline on the map) based on the current segment's speed in comparison with the average speed of the entire journey. This functionality should only take effect if the user has selected '**Color by Speed**' in the user settings of the Android application.

**Comment by akshaya13** [comment]
Solution:
This implementation addresses issue #67 by introducing dynamic color coding for the track based on Speed. 

In MapActivity.java, the proposed code snippet includes a method, getTrackColorbySpeed, which assigns colors (yellow, orange, or blue) to the track (polyline on the map) based on the current speed compared to the average speed.  This functionality is designed to take effect only if the user has selected 'Color by Speed' in the user settings of the Android application.

This implementation enhances the user experience by visually representing the speed variations along the tracked journey, providing users with a quick and intuitive way to interpret speed data. 

Screenshot of the code:
![Screenshot](https://github.com/rilling/OSMDashboardConcordia/assets/8524210/2c82beea-7e11-4e67-8a72-265d4aad0a53)
