### ISSUE TITLE
#Subtask 2 - Related to the issue #67 .A legend should be displayed to the user on the map

### ISSUE THREAD

**Issue by msrana25** [rilling/OSMDashboardConcordia#91]
**Is your feature request related to a problem? Please describe.**
Related to the issue #67 . Maps are missing a legend - A legend should be displayed to the user on the map

**Describe the solution you'd like**
A legend should be displayed to the user on the map, which illustrates the color coding of the polyline on the map. To implement this use case, additional layouts, views, and text views need to be added to the map.xml file present in the root directory **src/main/java/de/storchp/opentracks/osmplugin**.

**Comment by LucasChollet** [comment]
Solution:
This contributes to #67 by adding the required layout changes to support the introduction of the legend.

Stored in [map.xml](src/main/res/layout/map.xml), the layout describes how visual elements are organized inside the view. As the legend that we want to add has three distinct parts, we are going to add them separately. Indeed, each block contains a colored rectangle (containing the color information), and a text label to show the signification of the previously mentioned color. The final result can be shown here:
![Screenshot from 2023-11-27 01-08-26](https://github.com/rilling/OSMDashboardConcordia/assets/26030965/20c5e158-f193-40a4-8a92-e18c2f8a9cae)


Here are the code diff:
![yellow](https://github.com/rilling/OSMDashboardConcordia/assets/26030965/e0aa65b7-9a82-473c-83e6-cc7ac82f4cc6)
![orange](https://github.com/rilling/OSMDashboardConcordia/assets/26030965/e4fcf771-71bf-4c0b-9e39-ca0baf85fdca)
![blue](https://github.com/rilling/OSMDashboardConcordia/assets/26030965/81dd22c2-ee58-4c47-8ebf-3a0cfc4f42d9)
