### ISSUE TITLE
Subtask #1: Related to #69 Configure Statistics - Adding average speed to the strings.xml

### ISSUE THREAD

**Issue by aryansaxena094** [rilling/OSMDashboardConcordia#92]
## Description
To access the Strings.xml file, it is necessary to create entries for average speed strings. These entries will allow the application to display average speed in both kilometers per hour and miles per hour.

**Comment by YatishChutani** [comment]
Added the string for average speed in km/h in string.xml.
The necessary changes were made to the code and pushed from branch Group-13 to main after the review was done.

commit id: [d3077f3]
