### ISSUE TITLE
Subtask #2: Related to #69 Configure Statistics - Adding StatisticElement for Average Speed (Km/h)

### ISSUE THREAD

**Issue by aryansaxena094** [rilling/OSMDashboardConcordia#95]
## Description 

Implement the AVERAGE_SPEED_KM_H element to display the average speed. Taking the Strings from the String.utils provided.

**Comment by Khyati-Bareja** [comment]
The necessary changes were made to the code and pushed from branch Group-13 to main after the review was done.

commit id: [b118c6f](https://github.com/rilling/OSMDashboardConcordia/commit/b118c6ffdaf6acff781456a544b409a22b768be4)

**Comment by Khyati-Bareja** [comment]
Below are the changes made after Using the Average Speed specified in the TrackStatistics.java.
<img width="757" alt="Screenshot 2023-11-26 at 12 31 10 AM" src="https://github.com/rilling/OSMDashboardConcordia/assets/117713327/26aa0d91-9d9c-41a2-9e80-496f3f635ef2">
