### ISSUE TITLE
Subtask #3: Related to #69 Configure Statistics - Adding Average Speed km/h to Preference Utils

### ISSUE THREAD

**Issue by aryansaxena094** [rilling/OSMDashboardConcordia#97]
## Description

Currently, the PreferencesUtils class does not include the StatisticElement.AVERAGE_SPEED_MI_H.name() in the Unit_Statistic_Elements set for certain locales. This omission limits the application's ability to display average speed in miles per hour (mi/h) for users in those locales.

**Comment by i-sumitkumar** [comment]
Configure Statistics - Adding Average Speed km/h to Preference Utils 
The necessary changes were made to the code and pushed from branch Group-13 to main after the review was done.

commit id: ([c97847a](https://github.com/rilling/OSMDashboardConcordia/commit/c97847afd5de57d4c9607366d4240de50667abd6))
