### ISSUE TITLE
Subtask #4: Related to #69 Configure Statistics - Also Adding Average Speed String for MI/H

### ISSUE THREAD

**Issue by aryansaxena094** [rilling/OSMDashboardConcordia#99]
## Description

Coordinated with Team 16, in order to following imperial and metric systems accordingly. Added a String for the MI/H that can be accessed in the application.

**Comment by NehaVelagapudi** [comment]
## Description

Git commit ID - [[36f748a]
Post coordinating with **Group 16**. We added a String for the MI/H that can be accessed in the application in the strings.xml file


### Strings.xml - 
<img width="1470" alt="Screenshot 2023-11-25 at 11 37 03 PM" src="https://github.com/rilling/OSMDashboardConcordia/assets/52523435/01e4d0af-b737-4afa-b875-ad1a571fd98f">
